#!/bin/bash

# 🚀 Development Firebase Setup Helper Script
# This script helps you set up a separate Firebase project for development

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}╔══════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                                          ║${NC}"
echo -e "${BLUE}║        🔧 Development Firebase Configuration Setup 🔧                    ║${NC}"
echo -e "${BLUE}║                                                                          ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo -e "${YELLOW}⚠️  .env.local already exists!${NC}"
    echo ""
    read -p "Do you want to overwrite it? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}✅ Keeping existing .env.local${NC}"
        exit 0
    fi
fi

echo -e "${BLUE}This script will help you set up a development Firebase project.${NC}"
echo ""
echo -e "${YELLOW}Prerequisites:${NC}"
echo "  1. Create a new Firebase project (grampanchayat-dev) at:"
echo "     https://console.firebase.google.com/"
echo "  2. Add a Web app to the project"
echo "  3. Copy the Firebase configuration"
echo ""

read -p "Have you created a development Firebase project? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo -e "${YELLOW}📝 Please follow these steps:${NC}"
    echo ""
    echo "  1. Go to: https://console.firebase.google.com/"
    echo "  2. Click 'Add project'"
    echo "  3. Name: grampanchayat-dev"
    echo "  4. Disable Google Analytics (optional)"
    echo "  5. Click 'Create project'"
    echo "  6. Go to Project Settings → General"
    echo "  7. Scroll to 'Your apps' → Add app → Web"
    echo "  8. Register app and copy the config"
    echo ""
    echo "  Then run this script again!"
    echo ""
    exit 0
fi

echo ""
echo -e "${GREEN}Great! Let's set up your .env.local file.${NC}"
echo ""
echo -e "${YELLOW}Please enter your Firebase configuration values:${NC}"
echo -e "${BLUE}(You can find these in Firebase Console → Project Settings → Your apps)${NC}"
echo ""

# Collect Firebase config
read -p "API Key (VITE_FIREBASE_API_KEY): " API_KEY
read -p "Auth Domain (e.g., grampanchayat-dev.firebaseapp.com): " AUTH_DOMAIN
read -p "Project ID (e.g., grampanchayat-dev): " PROJECT_ID
read -p "Storage Bucket (e.g., grampanchayat-dev.firebasestorage.app): " STORAGE_BUCKET
read -p "Messaging Sender ID: " SENDER_ID
read -p "App ID: " APP_ID

# Optional measurement ID
echo ""
read -p "Do you have a Measurement ID? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    read -p "Measurement ID (e.g., G-XXXXXXXXXX): " MEASUREMENT_ID
    MEASUREMENT_LINE="VITE_FIREBASE_MEASUREMENT_ID=${MEASUREMENT_ID}"
else
    MEASUREMENT_LINE="# VITE_FIREBASE_MEASUREMENT_ID="
fi

# Create .env.local file
echo ""
echo -e "${BLUE}📝 Creating .env.local file...${NC}"

cat > .env.local << EOF
# =============================================================================
# 🔧 LOCAL DEVELOPMENT ENVIRONMENT
# =============================================================================
# Auto-generated by setup-dev-firebase.sh
# Last updated: $(date)
# =============================================================================

# Development Firebase Configuration
VITE_FIREBASE_API_KEY=${API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${SENDER_ID}
VITE_FIREBASE_APP_ID=${APP_ID}
${MEASUREMENT_LINE}

# Feature Flags - Development Mode
VITE_ENABLE_ANALYTICS=false
VITE_ENABLE_PERFORMANCE=false
VITE_ENABLE_APP_CHECK=false
VITE_ENABLE_DEBUG=true

# Environment identifier
VITE_ENVIRONMENT=development
VITE_SHOW_ENV_BADGE=true
EOF

echo ""
echo -e "${GREEN}✅ .env.local created successfully!${NC}"
echo ""

# Verify the file
echo -e "${BLUE}📋 Your configuration:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat .env.local | grep "^VITE_" | sed 's/VITE_FIREBASE_API_KEY=.*/VITE_FIREBASE_API_KEY=********** (hidden)/'
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if .gitignore has .env.local
if grep -q "\.env\.local" .gitignore 2>/dev/null; then
    echo -e "${GREEN}✅ .env.local is in .gitignore${NC}"
else
    echo -e "${YELLOW}⚠️  Adding .env.local to .gitignore...${NC}"
    echo ".env.local" >> .gitignore
    echo -e "${GREEN}✅ Added .env.local to .gitignore${NC}"
fi

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                                          ║${NC}"
echo -e "${GREEN}║                    ✅ Setup Complete! ✅                                  ║${NC}"
echo -e "${GREEN}║                                                                          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${YELLOW}📋 Next Steps:${NC}"
echo ""
echo "  1. ${BLUE}Set up Firestore in your dev project:${NC}"
echo "     https://console.firebase.google.com/project/${PROJECT_ID}/firestore"
echo ""
echo "  2. ${BLUE}Enable Authentication:${NC}"
echo "     https://console.firebase.google.com/project/${PROJECT_ID}/authentication"
echo "     - Enable Email/Password provider"
echo ""
echo "  3. ${BLUE}Enable Storage:${NC}"
echo "     https://console.firebase.google.com/project/${PROJECT_ID}/storage"
echo ""
echo "  4. ${BLUE}Create admin user:${NC}"
echo "     ${GREEN}node create-admin-user.js${NC}"
echo "     (or manually in Firebase Console → Authentication)"
echo ""
echo "  5. ${BLUE}Start development:${NC}"
echo "     ${GREEN}npm run dev${NC}"
echo ""
echo "  6. ${BLUE}Verify it's using dev project:${NC}"
echo "     - Open browser console"
echo "     - Look for: projectId: \"${PROJECT_ID}\""
echo ""

echo -e "${BLUE}════════════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}Now when you run 'npm run dev', it will use your development project!${NC}"
echo -e "${BLUE}Production deployments will still use the production project.${NC}"
echo -e "${BLUE}════════════════════════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${GREEN}Happy coding! 🚀${NC}"
echo ""
